### ISSUE TITLE
Purge unseen player settings

### ISSUE THREAD

**Issue by Chypik** [NewbieOrange/clicksort#10]
is it possible to synchronize the settings.yml file with the authorization plugin somehow? over time, this file will be very large

**Comment by NewbieOrange** [comment]
No, but we can store user settings in database.

**Comment by Chypik** [comment]
players come and go, the file gets big.

**Comment by NewbieOrange** [comment]
> players come and go, the file gets big.

You mean to have a purge feature to delete unseen players settings? Sure we can have that

**Comment by NewbieOrange** [comment]
Hi, @Chypik please test this new version with auto-purge and sqlite storage! (note: github can only upload zip files, need to unzip)

New config.yaml entries:
```yaml
# Interval of autopurge
autopurge_seconds: 3600
# Purge after player unseen for ... (e.g. 1m1d = 1month and 1day)
purge_after: 7d
```

[ClickSort-1.6.0-SNAPSHOT.zip](https://github.com/NewbieOrange/clicksort/files/7960521/ClickSort-1.6.0-SNAPSHOT.zip)
